format = """
[](fg:#2E3440)\
$directory\
[](fg:#2E3440 bg:#3B4252)\
$git_branch\
$git_status\
[](fg:#3B4252 bg:#434C5E)\
$buf\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#434C5E bg:#4C566A)\
$kubernetes\
$container\
$docker_context\
[](fg:#4C566A bg:#D8DEE9)\
$cmd_duration\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[buf]
symbol = "󰿘 "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 0
style = "bg:#D8DEE9 fg:#2E3440"
format = '[ $duration ]($style)'

[character]
success_symbol = "[](fg:#D8DEE9 bg:#D8DEE9)[](fg:#D8DEE9)"
error_symbol = "[](fg:#D8DEE9 bg:#BF616A)[](fg:#BF616A)"

[directory]
style = "bg:#2E3440 fg:#D8DEE9"
format = "[ $path $read_only ]($style)"
home_symbol = "󱂵 "
truncation_length = 3
truncation_symbol = "󰦩 "
read_only = "󰌾 "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[docker_context]
disabled = false
symbol = " "
style = "bg:#4C566A fg:#D8DEE9"
format = '[ $symbol $context ]($style) $path'

[kubernetes]
symbol = "󱃾 "
disabled = false
format = '[ $symbol $cluster ]($style)'
style = "bg:#4C566A fg:#D8DEE9"

[elixir]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "󰊢"
style = "bg:#3B4252 fg:#D8DEE9"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3B4252 fg:#D8DEE9"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#434C5E fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'
