# TODO: cleanup
format = """\
[╭─](bold #585858)\
[](#33658A)\
[\uf120 ](bg:#33658A)\
[](bg:#FF9248 fg:#33658A)\
[  ](bg:#FF9248 fg:#000000)\
$directory\
[](fg:#FF9248 bg:#FFEB95)\
$git_branch\
$git_status\
[](fg:#FFEB95 bg:#33658A)\
$username\
[ ](fg:#33658A)\
$fill \
$cmd_duration\
$java\
$python\
$nodejs\
$rust\
$git_metrics\
[](bright-green)\
$memory_usage\
[](bright-green)
[╰─ ](bold #585858)
"""

[fill]
symbol = "·"
style = "bold #585858"

[username]
show_always = true
style_user = "bg:#33658A"
style_root = "bg:#33658A"
format = '[   $user ](fg:white $style)'

[directory]
style = "bg:#FF9248 fg:black"
format = "[$path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "../"

[directory.substitutions]
"Documents" = "Documents  "
"Downloads" = "Downloads  "
"Music" = "Music  "
"Pictures" = "Pictures "

[git_branch]
symbol = " "
style = "bg:#FFEB95 fg:#000000"
format = '[[ $symbol $branch ](bg:#FFEB95 fg:000000)]($style)'

[git_status]
style = "bg:#FFEB95"
format = '[[($all_status$ahead_behind )](bg:#FFEB95 fg:#000000)]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[[](fg:#86BBD8)[$symbol ($version) ](bg:#86BBD8)[ ](fg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "bg:#AF400E"
format = '[[](fg:#AF400E)[$symbol ($version) ](bg:#AF400E)[ ](fg:#AF400E)]($style)'

[cmd_duration]
min_time = 1000
style = "bg:light blue"
show_milliseconds = false
format = "[[[](fg:#52A2DA) $duration](fg:black bg:#52A2DA) ](fg:#52A2DA)"

[memory_usage]
disabled = false
threshold = 0
format = "[ $ram](fg:black bg:bright-green)"

[java]
# Added kotlin files
detect_extensions = ["java", "class", "gradle", "jar", "cljs", "cljc", "kt", "kts"]
format = "[[[](fg:#FFA518) $version](fg:white bg:#FFA518) ](fg:#FFA518)"

[python]
format = "[[[](fg:#306998) $version](fg:#FFD43B bg:#306998) ](fg:#306998)"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = '[+$added]($added_style)/[-$deleted ]($deleted_style)'
