"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:peach)\
$os\
$username\
[](bg:yellow fg:peach)\
$directory\
[](bg:green fg:yellow)\
$git_branch\
$git_status\
[](bg:sapphire fg:green)\
$c\
$golang\
$java\
$nodejs\
$python\
$rust\
[](bg:mauve fg:sapphire)\
$docker_context\
[](bg:surface1 fg:mauve)\
$time\
[](fg:surface1)\
$character
"""

palette = "ayu_mirage"

[palettes.ayu_mirage]
rosewater = "#ffdfb3"
flamingo = "#f28779"
pink = "#f27983"
mauve = "#dfbfff"
red = "#ff6666"
maroon = "#f29e74"
peach = "#ffad66"
yellow = "#ffd173"
green = "#d5ff80"
teal = "#95e6cb"
sky = "#5ccfe6"
sapphire = "#73d0ff"
blue = "#80bfff"
lavender = "#b8cfe6"
text = "#cccac2"
subtext1 = "#afb3bb"
subtext0 = "#9da1aa"
overlay2 = "#8a9199"
overlay1 = "#707a8c"
overlay0 = "#576072"
surface2 = "#3f4757"
surface1 = "#282e3b"
surface0 = "#242936"
base = "#1f2430"
mantle = "#1a1f29"
crust = "#171b24"

[palettes.ayu_dark]
rosewater = "#e6c08a"
flamingo = "#f07178"
pink = "#f26d78"
mauve = "#d2a6ff"
red = "#d95757"
maroon = "#f29668"
peach = "#ff8f40"
yellow = "#ffb454"
green = "#aad94c"
teal = "#95e6cb"
sky = "#39bae6"
sapphire = "#59c2ff"
blue = "#73b8ff"
lavender = "#99adbf"
text = "#bfbdb6"
subtext1 = "#9da1aa"
subtext0 = "#848996"
overlay2 = "#6c7380"
overlay1 = "#555e73"
overlay0 = "#41495b"
surface2 = "#2d3442"
surface1 = "#1b1f29"
surface0 = "#161a24"
base = "#141821"
mantle = "#10141c"
crust = "#0d1017"

[palettes.ayu_light]
rosewater = "#d9b077"
flamingo = "#f07171"
pink = "#ff7383"
mauve = "#a37acc"
red = "#e65050"
maroon = "#ed9366"
peach = "#ff7e33"
yellow = "#f2a300"
green = "#86b300"
teal = "#4cbf99"
sky = "#55b4d4"
sapphire = "#399ee6"
blue = "#478acc"
lavender = "#787b80"
text = "#5c6166"
subtext1 = "#656c75"
subtext0 = "#6e7884"
overlay2 = "#778392"
overlay1 = "#828e9f"
overlay0 = "#99a4b2"
surface2 = "#b0b9c4"
surface1 = "#c8ced6"
surface0 = "#e0e4e8"
crust = "#f8f9fa"
mantle = "#fafafa"
base = "#fcfcfc"

[os]
disabled = false
style = "bg:peach fg:crust"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:peach fg:crust"
style_root = "bg:peach fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:yellow fg:crust"
format = "[   $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:sapphire fg:crust"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:sapphire fg:crust"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:sapphire fg:crust"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire fg:crust"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:sapphire fg:crust"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:sapphire fg:crust"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:mauve fg:crust"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface1 fg:text"
format = '[ 󰔟 $time ]($style)'

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
