"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#FEC7B4)\
$os\
[](bg:#864AF9 fg:#FEC7B4)\
$username\
[](bg:#F7418F fg:#864AF9)\
$directory\
[](fg:#F7418F bg:#E0AED0)\
$git_branch\
$git_status\
[](fg:#E0AED0 bg:#AC87C5)\
$python\
$nodejs\
$swift\
$rust\
$golang\
$php\
$ruby\
$julia\
[](fg:#AC87C5 bg:#756AB6)\
$time\
$battery\
[](fg:#756AB6)\
$line_break$character"""

[os]
disabled = false
style = "bg:#FEC7B4 fg:#0D1282"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "fg:#000000 bg:#864AF9"
style_root = "fg:#0D1282 bg:#F7418F"
format = '[ $user ]($style)'

[directory]
style = "fg:#1F2544 bg:#F7418F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#E0AED0"
format = '[[ $symbol $branch ](fg:#184D47 bg:#E0AED0)]($style)'

[git_status]
style = "bg:#E0AED0"
format = '[[($all_status$ahead_behind )](fg:#184D47 bg:#E0AED0)]($style)'

[python]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[nodejs]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[rust]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[golang]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[php]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[ruby]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[julia]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[java]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[swift]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#1B3C73 bg:#AC87C5)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ♥  $time ](fg:#F7EA00 bg:#756AB6)]($style)'

[battery]
disabled = false
full_symbol = '󰁹'
charging_symbol = '󰂄 '
discharging_symbol = '󰂃'
empty_symbol = '󰂎'
format = '[$symbol$percentage]($style)'

[[battery.display]]
threshold = 10
style = 'fg:#FF204E bg:#756AB6'

[[battery.display]]
threshold = 70
style = "fg:#FFF455 bg:#756AB6"

[[battery.display]]
threshold = 100
style = "fg:#C2F8CB bg:#756AB6"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[✓](bold fg:#65B741)'
error_symbol = '[✗](bold fg:#E72929)'
