"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$pixi\
$time\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_orange bold"
format = '[$symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:color_orange bold"
style_root = "fg:color_red bold"
format = '[$user ]($style)'

[directory]
style = "fg:color_yellow bold"
format = 'in [$path ]($style)'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:color_aqua"
format = 'on [$symbol $branch ]($style)'

[git_status]
style = "fg:color_red"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[c]
symbol = " "
style = "fg:color_blue"
format = 'via [$symbol$version ]($style)'

[cpp]
symbol = " "
style = "fg:color_blue"
format = 'via [$symbol$version ]($style)'

[rust]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[golang]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[php]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[java]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[kotlin]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[haskell]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[python]
symbol = ""
style = "fg:color_blue"
format = 'via [$symbol $version ]($style)'

[docker_context]
symbol = ""
style = "fg:color_purple"
format = 'via [$symbol $context ]($style)'

[conda]
style = "fg:color_purple"
format = 'via [$symbol $environment ]($style)'

[pixi]
style = "fg:color_purple"
format = 'via [$symbol$version( $environment) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bold"
format = 'at [  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
