"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#16161D)\
$os\
$username\
[](bg:#223249 fg:#16161D)\
$directory\
[](fg:#223249 bg:#2A2A37)\
$git_branch\
$git_status\
[](fg:#2A2A37 bg:#363646)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#363646 bg:#54546D)\
$docker_context\
[](fg:#54546D bg:#658594)\
$time\
[ ](fg:#658594)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#16161D fg:#DCD7BA"
style_root = "bg:#16161D fg:#DCD7BA"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#16161D fg:#DCD7BA"
disabled = true # Disabled by default

[directory]
style = "bg:#223249 fg:#DCD7BA"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#54546D fg:#DCD7BA"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#2A2A37 fg:#DCD7BA"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#2A2A37 fg:#DCD7BA"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#363646 fg:#DCD7BA"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#658594 fg:#DCD7BA"
format = '[ ♥ $time ]($style)'
