"$schema" = 'https://starship.rs/config-schema.json'

[azure]
symbol = "☁️ "

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[fossil_branch]
symbol = "⎇ "

[git_branch]
symbol = "⎇ "

[hg_branch]
symbol = "⎇ "

[nodejs]
symbol = "[⬢](bold green) "

[pijul_channel]
symbol = "⎇ "

[pulumi]
symbol = "🧊 "
