files:
  - source: /docs/**/*.md
    ignore:
      - /docs/%two_letters_code%
      - /docs/guide
    translation: /docs/%two_letters_code%/**/%original_file_name%
  - source: /README.md
    translation: /%file_name%.%two_letters_code%.%file_extension%
