files:
  - source: /docs/**/*.md
    ignore:
      - /docs/%two_letters_code%
      - /docs/%locale%
      - /docs/guide
      - /docs/translations
    translation: /docs/%locale%/**/%original_file_name%
  - source: /README.md
    translation: /docs/%locale%/guide/%file_name%.%file_extension%
