[advisories]
ignore = [
    # difference is unmaintained
    # Only used in test code
    # Tracked in #2835
    "RUSTSEC-2020-0095",
    # Out-of-bounds write in nix::unistd::getgrouplist
    # Tracked in #3140
    "RUSTSEC-2021-0119",
    # Potential segfault in the time crate
    # chrono dependency, but vulnerable function is never called
    # Tacked in #3163
    "RUSTSEC-2020-0071",
    # chrono: Potential segfault in localtime_r invocations
    # starship avoids setting any environment variables to avoid this issue
    # Tracked in #3166
    "RUSTSEC-2020-0159",
]