jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
      # # Temporarily disabling Windows tests while I'm away
      # # Will reenable Windows tests once I'm able to troubleshoot Windows bugs
      # Windows:
      #   vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: azure-setup-test-env.yml

  # "-Z unstable-options" is required for "--include-ignored"
  - script: cargo test -- -Z unstable-options --include-ignored
    displayName: cargo test
