jobs:
# Check formatting
- job: ${{ parameters.name }}
  displayName: Check rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: \
        rustup install stable
    # - template: azure-install-rust.yml
    #   parameters:
    #     rust_version: stable
    - script: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - script: |
        cargo fmt --all -- --check
      displayName: Check formatting
