jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
      Windows:
        vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: azure-setup-test-env.yml

  - script: cargo install cargo-tarpaulin -f
    displayName: "Install tarpaulin"
    condition: eq(variables['vmImage'], 'ubuntu-16.04')

  - script: cargo test -- --ignored
    displayName: cargo test
