jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
      Windows:
        vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: azure-setup-test-env.yml

  - script: cargo test -- --ignored
    displayName: cargo test
    condition: not(eq(variables['vmImage'], 'ubuntu-16.04'))

  - script: |
        cargo install cargo-tarpaulin -f
        cargo tarpaulin --ignored --out Xml
        bash <(curl -s https://codecov.io/bash)
    displayName: "Cargo test w/ coverage"
    condition: eq(variables['vmImage'], 'ubuntu-16.04')
