# SUPPORTED TARGETS https://github.com/rust-embedded/cross#supported-targets

parameters:
  rust_version: stable
  check_target: []
  test_targets: []

jobs:
- job: ${{ parameters.name }}
  displayName: ${{parameters.displayName}}
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: install-cross-rust.yml

    # Checking all targets
    - ${{ each check_target in parameters.check_targets }}:
            - script: cargo clean
            - script: cross check --target  ${{ check_target }}

    # Testing targets
    - ${{ each test_target in parameters.test_targets }}:
       - script: cross test --target ${{ test_target }} -- --include-ignored 
       - script: cargo clean
