parameters:
  rust_version: stable

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: install-rust.yml

      - script: cargo check
        displayName: Check features
