parameters:
  rust_version: stable

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: install-rust.yml

      - script: cargo clippy -- -D clippy::all
        displayName: Run clippy
