parameters:
  rust_version: stable

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }} ${{parameters.rust_version}}
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04

        ${{ if parameters.cross }}:
          MacOS:
            vmImage: macOS-10.13
          Windows:
            vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:
      - template: install-rust.yml
      - template: setup-test-env.yml
      - script: |
          cargo test
        env:
          CI: "true"
        displayName: cargo test
