name: Dependabot

on: [pull_request]

jobs:
  auto_merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_GITHUB_API_TOKEN }}
