name: Format + Docs Workflow
on:
  push:
    paths: ["docs/**", "**.md", "**.toml", "**.js", "**.json", "**.ts"]
  pull_request:
    paths: ["docs/**", "**.md", "**.toml", "**.js", "**.json", "**.ts"]

jobs:
  # Run the dprint code formatter for documentation
  dprint:
    name: Dprint [Docs Formatter]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Docs | Format
        uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3

  # Validate preset files
  taplo:
    name: Taplo [Preset schema validation]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install | Taplo
        uses: taiki-e/install-action@7a4939c09608b2a1986b484eca1d16fd0db8ebef # v2.75.5
        with:
          tool: taplo-cli@0.10.0
      - name: Presets | Validate with schema
        run: taplo lint --schema "file://${GITHUB_WORKSPACE}/.github/config-schema.json" docs/public/presets/toml/*.toml

  # If this is not a Crowdin PR, block changes to translated documentation
  block-crowdin:
    name: Block Translated Changes
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'i18n_master' }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Prevent File Change
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { execSync } = require('child_process');
            const pattern = /^docs\/[a-z][a-z][a-z]?-[A-Z][A-Z]?\/.*$/;
            const base = context.payload.pull_request.base.sha;
            const head = context.payload.pull_request.head.sha;

            const result = execSync(`git diff --name-only ${base} ${head}`).toString().split('\n');

            for (const file of result) {
              if (pattern.test(file)) {
                core.setFailed(`To avoid conflicts, changes to the translated documentation are only allowed via Crowdin at https://translate.starship.rs.`);
                break;
              }
            }

  # Vitepress build
  vitepress:
    name: Vitepress [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.15.0
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Setup | Install dependencies
        run: npm install
        working-directory: docs

      - name: Build | Build docs site
        run: npm run build
        working-directory: docs
