name: Spell Check
on: [pull_request]

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: crate-ci/typos@7c572958218557a3272c2d6719629443b5cc26fd # v1.45.2
